CLASSEPATH =  .:src:../../../common/lib/ant.jar:../../../common/lib/commons-collections.jar:../../../common/lib/commons-dbcp-1.1.jar:../../../common/lib/commons-el.jar:../../../common/lib/commons-pool-1.1.jar:../../../common/lib/jasper-compiler.jar:../../../common/lib/jasper-runtime.jar:../../../common/lib/jmx.jar:../../../common/lib/jsp-api.jar:../../../common/lib/naming-common.jar:../../../common/lib/naming-factory.jar:../../../common/lib/naming-java.jar:../../../common/lib/naming-resources.jar:../../../common/lib/naming-resources.jar::../../../common/lib/servlet-api.jar

compile :
	javac -d classes -classpath $(CLASSEPATH) src/tp/jsp/*.java
